name: IM939
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.1.*
  - geopandas=0.14.*
  - pandas=2.1.*
  - pip
  - python=3.11.4
  - jupyterlab
  - openpyxl
  - scikit-learn
  - seaborn
  - pip:
    - ghp-import
    - jupyterlab-quarto
    - lckr-jupyterlab-variableinspector