name: IM939

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.14.6
  - altair=6.*
  - geopandas
  - pandas=3.*
  - pip
  - jupyterlab
  - nbstripout
  - openpyxl
  - scikit-learn
  - seaborn=0.13.*
  - pip:
      - ghp-import
      - jupyterlab-quarto
